# Generated by Django 5.1.6 on 2025-03-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bids_id_alter_comments_id_alter_listings_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name_plural': 'Listings'},
        ),
        migrations.RemoveField(
            model_name='listings',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='listings',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
