# Generated by Django 5.1.6 on 2025-03-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listings_image_filename_listings_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
