# Generated by Django 5.1.6 on 2025-03-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlists',
            options={'verbose_name_plural': 'Watchlists'},
        ),
    ]
